name: Harvest seeds → Hub PR

on:
  workflow_dispatch:
  schedule:
    - cron: "17 9 * * *"  # 09:17 UTC daily, tune as you like

jobs:
  harvest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      HUB_OWNER: ${{ secrets.HUB_OWNER }}
      HUB_REPO:  ${{ secrets.HUB_REPO }}
      HUB_PAT:   ${{ secrets.HUB_PAT }}
      HUB_RAW:   https://raw.githubusercontent.com/${{ secrets.HUB_OWNER }}/${{ secrets.HUB_REPO }}/main
    steps:
      - name: Checkout Archive
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml jsonschema requests github3.py

      - name: Pull registry & schemas from hub
        run: |
          mkdir -p tmp/hub
          curl -fsSL "$HUB_RAW/seeds/registry.yml" -o tmp/hub/registry.yml
          curl -fsSL "$HUB_RAW/schema/glossary.schema.yml" -o tmp/hub/glossary.schema.yml
          curl -fsSL "$HUB_RAW/schema/tags.schema.yml" -o tmp/hub/tags.schema.yml

      - name: Harvest seeds from suns
        run: |
          python scripts/pull_seeds_to_hub.py \
            --registry tmp/hub/registry.yml \
            --out-dir tmp/hub_update \
            --schemas-dir tmp/hub

      - name: Prepare PR to hub (if changes)
        run: |
          if [ -d tmp/hub_update ] && [ -n "$(ls -A tmp/hub_update)" ]; then
            echo "Changes found; preparing PR."
          else
            echo "No changes detected."
            echo "no_changes=true" >> $GITHUB_ENV
          fi

      - name: Create PR in hub
        if: env.no_changes != 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.HUB_PAT }}
          commit-message: "Archive harvest: sync seeds from constellation"
          committer: "archive-bot <actions@users.noreply.github.com>"
          author: "archive-bot <actions@users.noreply.github.com>"
          title: "Archive harvest: sync seeds from constellation"
          body: "Automated sync of seeds from module repos → hub. Generated by The Archive."
          branch: "archive/harvest-seeds"
          base: "main"
          signoff: true
          delete-branch: true
          add-paths: |
            seeds/**
          push-to-fork: false
          # Add files
          # We copy files into the repo before create-pull-request runs by checking out the hub and staging:
          # (do it in a separate step)
      - name: Checkout hub and stage files
        if: env.no_changes != 'true'
        run: |
          git config --global user.name "archive-bot"
          git config --global user.email "actions@users.noreply.github.com"

          git clone "https://${HUB_PAT}@github.com/${HUB_OWNER}/${HUB_REPO}.git" hub
          rsync -av --delete tmp/hub_update/ hub/seeds/
          cd hub
          git add seeds || true
          if git diff --cached --quiet; then
            echo "No staged changes after rsync."; exit 0
          fi
          git commit -m "Archive harvest: sync seeds from constellation"
