name: Archive Pulses

on:
  schedule:
    - cron: "20 9 * * *"    # daily at 09:20 UTC
  workflow_dispatch:        # allow manual run

permissions:
  contents: write           # allow committing updated index
  issues: write             # if you choose to open issues
  

jobs:
  pulse:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FOURTWENTY_TOPIC: fourtwentyanalytics   # used if you switch to topic discovery
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install pyyaml requests
      - name: Run Archive pulse
        run: python scripts/pulse_archive.py
      - name: Commit updates (if any)
        run: |
          git config user.name  "Archive Pulse Bot"
          git config user.email "actions@github.com"
          git add archive/pulse_badge.json archive/modules_index.json archive/signal_beacon.json README.md || true
          git diff --quiet && echo "No changes" || git commit -m "chore(pulse): refresh modules index"
          git push
