name: Pulse Constellation

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run without committing/pushing changes"
        required: false
        type: boolean
        default: false
  push:
    paths:
      - "scripts/pulse-constellation.sh"
      - "signals/**"
      - ".github/workflows/pulse-constellation.yml"
  schedule:
    # 09:00 America/New_York ≈ 13:00 UTC (update if you want a different local time)
    - cron: "0 13 * * *"

permissions:
  contents: write

jobs:
  pulse:
    runs-on: ubuntu-latest
    concurrency:
      group: pulse-constellation-${{ github.ref }}
      cancel-in-progress: false

    env:
      HUB_PAT: ${{ secrets.HUB_PAT }}      # Only needed if your script touches other repos/APIs beyond GITHUB_TOKEN
      HUB_OWNER: zbreeden
      HUB_REPO: archive-model
      DRY_RUN: ${{ inputs.dry_run && '1' || '0' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git identity for commits
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Verify files present
        run: |
          echo "Repo root: $(pwd)"
          ls -la
          echo "--- scripts dir ---"
          ls -la scripts || true
          test -f scripts/pulse-constellation.sh || (echo "scripts/pulse-constellation.sh not found" && exit 1)

      - name: Ensure script is LF & executable
        run: |
          # Normalize CRLF (prevents /usr/bin/env: 'bash\r': No such file or directory)
          sed -i 's/\r$//' scripts/pulse-constellation.sh
          chmod +x scripts/pulse-constellation.sh
          head -n1 scripts/pulse-constellation.sh | sed -e 's/^/shebang: /'

      - name: Pre-flight info
        run: |
          echo "Branch: $GITHUB_REF_NAME"
          echo "Dry run (env DRY_RUN): ${DRY_RUN:-0}"
          bash --version
          git status --porcelain

      - name: Run pulse script
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # For pushes to *this* repo
          HUB_PAT: ${{ secrets.HUB_PAT }}
          HUB_OWNER: zbreeden
          HUB_REPO: archive-model
        run: |
          set -euo pipefail
          bash scripts/pulse-constellation.sh

      - name: Commit & push any changes
        if: ${{ inputs.dry_run != true }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "Pulse: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes to commit."
          fi
